### ISSUE TITLE
Add support for asterisk CLI by using a web terminal (ttyd)

### ISSUE THREAD

**Issue by nanosonde** [TECH7Fox/Asterisk-add-on#104]
It would be nice if we would have access to the asterisk CLI inside the addon container by providing a web-based terminal emulator for it.
This would work the same way as the official HA SSH addon by using the daemon ttyd: https://github.com/tsl0922/ttyd

It seems to be really simple. See the examples here: https://github.com/tsl0922/ttyd/wiki/Example-Usage

Just start the following in the container:
```
ttyd asterisk -rvvvvddd
```

**Comment by felipecrs** [comment]
The exact same thing can be achieved by using the SSH addon, by executing:

```console
docker exec -it addon_b35499aa_asterisk asterisk -rvvvvddd
```

Inside of the SSH addon. Perhaps we just need to document it?

**Comment by nanosonde** [comment]
Ok. I was not aware that the SSH addon support running docker CLI.

I think that this should be sufficient.
I will close this ticket.
