### ISSUE TITLE
Remove S6 workaround in Dockerfile

### ISSUE THREAD

**Issue by nanosonde** [TECH7Fox/Asterisk-add-on#111]
Can the workaround be removed?
The mentioned issue https://github.com/hassio-addons/addon-base-python/issues/102 was closed.
Please check.

https://github.com/TECH7Fox/Asterisk-add-on/blob/446c69397e9a69bb80cf59c1c4985eec190eafca/asterisk/Dockerfile#L9-L10

**Comment by felipecrs** [comment]
No, as it wasn't released yet.

**Comment by nanosonde** [comment]
Ok, I would recommend to keep the issue open.
