### ISSUE TITLE
Opus codec binary only for x86/amd64 architecture available

### ISSUE THREAD

**Issue by nanosonde** [TECH7Fox/Asterisk-add-on#118]
The opus codec is downloaded from Digium servers while building asterisk.
However, this version only support x86 and amd64 architecure. It also comes with a Digium license.

There is an open source version available here: https://packages.debian.org/bullseye/asterisk-opus

We should switch to this version as it provides support for other architectures as well.

**Comment by nanosonde** [comment]
It seems taht even Debian Bookworm does not provide the opus codex for Asterisk 18 anymore:
https://packages.debian.org/de/bookworm/asterisk

![grafik](https://user-images.githubusercontent.com/2073569/158057756-952f62f3-880e-4447-be3b-4f5831289e27.png)

**Comment by nanosonde** [comment]
Ah, but there seems to be something for 18.10.1:
https://salsa.debian.org/pkg-voip-team/asterisk/-/tree/upstream/18.10.1_dfsg+_cs6.10.40431411/Xopus

**Comment by nanosonde** [comment]
Fixed in https://github.com/TECH7Fox/Asterisk-add-on/pull/116/commits/005dccc05f15e0fb67fdefd403e36bec678c5b1b.

**Comment by felipecrs** [comment]
I know nothing about this... why do we need this codec? Did we have it before? Perhaps we can just skip it.

**Comment by nanosonde** [comment]
AFAIK this is the only audio codec supported by WebRTC if you want HD audio.
Otherwise we would only have alaw and ulaw codecs.
Opis included in most (all?) browsers.

**Comment by felipecrs** [comment]
Got it. Thank you for educating me on this :)

**Comment by nanosonde** [comment]
I just checked again.
https://datatracker.ietf.org/doc/html/rfc7874#page-2

Alaw, Ulaw and Opus are mandatory for WebRTC.
