### ISSUE TITLE
Document how configure Dahua VTO doorbell to integrate with the add-on

### ISSUE THREAD

**Issue by felipecrs** [TECH7Fox/Asterisk-add-on#15]
Open questions:

1. What configurations are needed in the add-on itself?
2. What to fill in:

http://192.168.1.40/#/Network
![image](https://user-images.githubusercontent.com/29582865/148113791-6e208481-5dc0-4711-bcf4-883e46670b57.png)

Especially the two usernames and passwords.

**Comment by dernassesmart** [comment]
Is the port (5060) correct? I thought it must be 8089?
Thank you in advance!

**Comment by pergolafabio** [comment]
Yes, ,5060 is correct, 8089 is only for websocket

**Comment by dernassesmart** [comment]
Thank you very much!

**Comment by felipecrs** [comment]
![image](https://user-images.githubusercontent.com/29582865/148691410-64faf7a3-78b5-4931-8149-c66d1c4209f7.png)

**Comment by felipecrs** [comment]
![image](https://user-images.githubusercontent.com/29582865/148691564-cf0ccfc2-c533-492f-a6a7-15e431d5f345.png)

1. The number which the doorbell will call. Make sure there is a `sipjs-card` with that number.
2. The number of the doorbell, make sure you created an extension for it in `/config/asterisk/sip_custom.conf`.

Here is my `sip_custom.conf`:

```ini
; Place your own extensions here.

[8001]
type=friend
host=dynamic
context=default
transport=udp
username=8001
secret=1234
```

**Comment by TECH7Fox** [comment]
Made a [wiki page](https://github.com/TECH7Fox/Asterisk-add-on/wiki/Configure-Dahua-VTO-doorbell#how-to-configure-the-dahua-vto-doorbell-with-the-asterisk-addon) for this. If you want to add/change a page you should be able to do that directly.

**Comment by felipecrs** [comment]
Very nice! I think we only need some examples of the sipjs-card configuration now.

**Comment by TECH7Fox** [comment]
> Very nice! I think we only need some examples of the sipjs-card configuration now.

Not needed anymore because of the new editor. May need to explain some of the options like camera, but I will do that in the readme.

**Comment by pergolafabio** [comment]
What file are you editing? Are you using sip or pjsip?

**Comment by sohaibid** [comment]
Only /config/asterisk/sip_custom.conf as the above ..
[8001]
type=friend
host=dynamic
context=default
transport=udp
username=8001
secret=1234

**Comment by pergolafabio** [comment]
Are you sure you have enabled chan_sip?
It's by default disabled, since it's now pjsip, so the docs are outdated

**Comment by sohaibid** [comment]
Where and how to disable it?

**Comment by pergolafabio** [comment]
Use pjsip instead, not chan_sip , it's deprecated, have a look in the manuals how to use pjsip

**Comment by sohaibid** [comment]
I have created a file /config/asterisk/sip_custom.conf with the below config as my VTO EXT is 8001 with password 1234
[8000]
type = endpoint
context = default
disallow = all
allow = alaw,ulaw          ; Audio codecs
allow=h264                 ; Video codecs
direct_media_method=invite
dtmf_mode=info
callerid="Doorbell" <8000>
force_rport=no
aors= 8000
auth = auth8000

[8000]
type = aor
max_contacts = 1

[auth8000]
type=auth
auth_type=userpass
password=1234        ; Set your password here
username=8001

but still getting  NOTICE[401]: res_pjsip/pjsip_distributor.c:676 log_failed_request: Request 'REGISTER' from '<sip:8001@192.168.1.102>' failed for '192.168.1.110:5060' (callid: 950840859@192.168.1.110) - No matching endpoint found

**Comment by pergolafabio** [comment]
Created it? It should be there by default? Maybe try to uninstall reinstall addon

**Comment by sohaibid** [comment]
[8001]
type = endpoint
context = default
disallow = all
allow = alaw,ulaw          ; Audio codecs
allow=h264                 ; Video codecs
direct_media_method=invite
dtmf_mode=info
callerid="Doorbell" <8001>
force_rport=no
aors= 8001
auth = auth8001

[8001]
type = aor
max_contacts = 1

[auth8001]
type=auth
auth_type=userpass
password=1234        ; Set your password here
username=8001

the same,,

**Comment by sohaibid** [comment]
do you have TeamViewer? :)

**Comment by pergolafabio** [comment]
Try to uninstall addon, normally the file is already there, you don't need to create it... 
Change the file afterward, then restart addon, then they again

**Comment by sohaibid** [comment]
The same :(

**Comment by TECH7Fox** [comment]
@sohaibid you say `/config/asterisk/pjsip_custom.conf` but it should be `/config/asterisk/custom/pjsip_custom.conf`.

**Comment by sohaibid** [comment]
@TECH7Fox the same result. :-(

**Comment by sohaibid** [comment]
The custom folder was empty.
The default folder have the same file name but every time I edit it the default value come back after restart the add-on.
I have tried to reinstall the add-on but nothing changed.

**Comment by sohaibid** [comment]
@pergolafabio do you mean coping all files or pacific files?
As I see the default files in the default folder are not active as the commands starts with ; .

**Comment by TECH7Fox** [comment]
@pergolafabio that's not really the point of the new file system. Only the files you want to change should be in custom, so when asterisk updates and the default configs change it still works.

**Comment by pergolafabio** [comment]
Ahh, I have them all there :-)

**Comment by TECH7Fox** [comment]
@sohaibid the anything in the custom folder overrides the default folder and then gets used by asterisk. make sure you only have the pjsip_custom.conf in the custom folder. 

Then check the add-on console for any errors. Maybe your config is incorrect. Did you copy it from the sip-hass docs?

**Comment by sohaibid** [comment]
Still did not work, 
I have followed this link https://tech7fox.github.io/sip-hass-docs/docs/add-on/guides/doorbell 
with changing all 8000 to 8001 as it is my VTO ext.

**Comment by pergolafabio** [comment]
You actually restart the addon when changing files?

Can you copy paste full content of that file?

**Comment by sohaibid** [comment]
After deleting the files and install the add-on again I got below :

[May 17 21:12:17] DEBUG[396]: res_pjsip/pjsip_distributor.c:471 ast_sip_get_distributor_serializer: Calculated serializer pjsip/distributor-00000029 to use for Request msg REGISTER/cseq=1 (rdata0x7f68012d18)
[May 17 21:12:17] DEBUG[397]: res_pjsip_endpoint_identifier_ip.c:275 common_identify: No identify sections to match against
[May 17 21:12:17] DEBUG[397]: res_pjsip_endpoint_identifier_user.c:148 username_identify: Attempting identify by From username '8001' domain '192.168.1.102'
[May 17 21:12:17] DEBUG[397]: res_pjsip_endpoint_identifier_user.c:160 username_identify: Identified by From username '8001' domain '192.168.1.102'
[May 17 21:12:17] DEBUG[397]: res_pjsip_authenticator_digest.c:471 digest_check_auth: Using default realm 'asterisk' on incoming auth 'auth8001'.
[May 17 21:12:17] DEBUG[397]: res_pjsip_authenticator_digest.c:358 verify: Realm: asterisk  Username: 8001  Result: NOAUTH
[May 17 21:12:18] DEBUG[396]: res_pjsip/pjsip_distributor.c:393 find_dialog: Could not find matching transaction for Request msg REGISTER/cseq=2 (rdata0x7f68012d18)
[May 17 21:12:18] DEBUG[396]: res_pjsip/pjsip_distributor.c:471 ast_sip_get_distributor_serializer: Calculated serializer pjsip/distributor-00000029 to use for Request msg REGISTER/cseq=2 (rdata0x7f68012d18)
[May 17 21:12:18] DEBUG[397]: res_pjsip_endpoint_identifier_ip.c:275 common_identify: No identify sections to match against
[May 17 21:12:18] DEBUG[397]: res_pjsip_endpoint_identifier_user.c:148 username_identify: Attempting identify by From username '8001' domain '192.168.1.102'
[May 17 21:12:18] DEBUG[397]: res_pjsip_endpoint_identifier_user.c:160 username_identify: Identified by From username '8001' domain '192.168.1.102'
[May 17 21:12:18] DEBUG[397]: res_pjsip_authenticator_digest.c:471 digest_check_auth: Using default realm 'asterisk' on incoming auth 'auth8001'.
[May 17 21:12:18] DEBUG[397]: res_pjsip_authenticator_digest.c:358 verify: Realm: asterisk  Username: 8001  Result: NOAUTH
[May 17 21:12:20] DEBUG[396]: res_pjsip/pjsip_distributor.c:393 find_dialog: Could not find matching transaction for Request msg REGISTER/cseq=3 (rdata0x7f68012d18)
[May 17 21:12:20] DEBUG[396]: res_pjsip/pjsip_distributor.c:471 ast_sip_get_distributor_serializer: Calculated serializer pjsip/distributor-00000029 to use for Request msg REGISTER/cseq=3 (rdata0x7f68012d18)
[May 17 21:12:20] DEBUG[397]: res_pjsip_endpoint_identifier_ip.c:275 common_identify: No identify sections to match against
[May 17 21:12:20] DEBUG[397]: res_pjsip_endpoint_identifier_user.c:148 username_identify: Attempting identify by From username '8001' domain '192.168.1.102'
[May 17 21:12:20] DEBUG[397]: res_pjsip_endpoint_identifier_user.c:160 username_identify: Identified by From username '8001' domain '192.168.1.102'
[May 17 21:12:20] DEBUG[397]: res_pjsip_authenticator_digest.c:471 digest_check_auth: Using default realm 'asterisk' on incoming auth 'auth8001'.
[May 17 21:12:20] DEBUG[397]: res_pjsip_authenticator_digest.c:358 verify: Realm: asterisk  Username: 8001  Result: NOAUTH
[May 17 21:12:21] DEBUG[396]: res_pjsip/pjsip_distributor.c:393 find_dialog: Could not find matching transaction for Request msg REGISTER/cseq=4 (rdata0x7f68012d18)
[May 17 21:12:21] DEBUG[396]: res_pjsip/pjsip_distributor.c:471 ast_sip_get_distributor_serializer: Calculated serializer pjsip/distributor-00000029 to use for Request msg REGISTER/cseq=4 (rdata0x7f68012d18)
[May 17 21:12:21] DEBUG[397]: res_pjsip_endpoint_identifier_ip.c:275 common_identify: No identify sections to match against
[May 17 21:12:21] DEBUG[397]: res_pjsip_endpoint_identifier_user.c:148 username_identify: Attempting identify by From username '8001' domain '192.168.1.102'
[May 17 21:12:21] DEBUG[397]: res_pjsip_endpoint_identifier_user.c:160 username_identify: Identified by From username '8001' domain '192.168.1.102'
[May 17 21:12:21] DEBUG[397]: res_pjsip_authenticator_digest.c:471 digest_check_auth: Using default realm 'asterisk' on incoming auth 'auth8001'.
[May 17 21:12:21] DEBUG[397]: res_pjsip_authenticator_digest.c:358 verify: Realm: asterisk  Username: 8001  Result: NOAUTH
[May 17 21:12:22] DEBUG[396]: res_pjsip/pjsip_distributor.c:393 find_dialog: Could not find matching transaction for Request msg REGISTER/cseq=5 (rdata0x7f68012d18)
[May 17 21:12:22] DEBUG[396]: res_pjsip/pjsip_distributor.c:471 ast_sip_get_distributor_serializer: Calculated serializer pjsip/distributor-00000029 to use for Request msg REGISTER/cseq=5 (rdata0x7f68012d18)
[May 17 21:12:22] DEBUG[397]: res_pjsip_endpoint_identifier_ip.c:275 common_identify: No identify sections to match against
[May 17 21:12:22] DEBUG[397]: res_pjsip_endpoint_identifier_user.c:148 username_identify: Attempting identify by From username '8001' domain '192.168.1.102'
[May 17 21:12:22] DEBUG[397]: res_pjsip_endpoint_identifier_user.c:160 username_identify: Identified by From username '8001' domain '192.168.1.102'
[May 17 21:12:22] DEBUG[397]: res_pjsip_authenticator_digest.c:471 digest_check_auth: Using default realm 'asterisk' on incoming auth 'auth8001'.
[May 17 21:12:22] DEBUG[397]: res_pjsip_authenticator_digest.c:358 verify: Realm: asterisk  Username: 8001  Result: NOAUTH

**Comment by pergolafabio** [comment]
Post your config

**Comment by sohaibid** [comment]
[8001]
type = endpoint
context = default
disallow = all
allow = alaw,ulaw          ; Audio codecs
allow=h264                 ; Video codecs
direct_media_method=invite
dtmf_mode=info
callerid="Doorbell" <8001>
force_rport=no
aors= 8001
auth = auth8001

[8001]
type = aor
max_contacts = 1

[auth8001]
type=auth
auth_type=userpass
password=Maineusa1     ; Set your password here
username=8001


![image](https://github.com/TECH7Fox/asterisk-hass-addons/assets/39695223/fe5560f7-8fa5-414b-beed-98791735925c)
![Capture](https://github.com/TECH7Fox/asterisk-hass-addons/assets/39695223/6e8b4a65-6922-481e-bafb-7a962b8116ed)

**Comment by pergolafabio** [comment]
Try this config, example for 6000


```
[6000]
type=endpoint
context=default
disallow=all
allow=ulaw
allow=h264
auth=auth6000
aors=6000
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
direct_media=no
max_audio_streams=10
max_video_streams=10
from_domain=asterisk.com


[auth6000]
type=auth
auth_type=userpass
password=xxx
username=6000
 
[6000]
type=aor
qualify_frequency=30
max_contacts=1
remove_existing=yes
remove_unavailable=yes
```

**Comment by sohaibid** [comment]
This is the result, I just changed every 6000 to 8001 
[May 17 21:28:17] DEBUG[397]: res_pjsip/pjsip_distributor.c:471 ast_sip_get_distributor_serializer: Calculated serializer pjsip/distributor-0000003a to use for Request msg REGISTER/cseq=1 (rdata0x558fc55e28)
[May 17 21:28:17] DEBUG[398]: res_pjsip_endpoint_identifier_ip.c:275 common_identify: No identify sections to match against
[May 17 21:28:17] DEBUG[398]: res_pjsip_endpoint_identifier_user.c:148 username_identify: Attempting identify by From username '8001' domain '192.168.1.102'
[May 17 21:28:17] DEBUG[398]: res_pjsip_endpoint_identifier_user.c:160 username_identify: Identified by From username '8001' domain '192.168.1.102'
[May 17 21:28:17] DEBUG[398]: res_pjsip_authenticator_digest.c:471 digest_check_auth: Using default realm 'asterisk' on incoming auth 'auth8001'.
[May 17 21:28:17] DEBUG[398]: res_pjsip_authenticator_digest.c:358 verify: Realm: asterisk  Username: 8001  Result: NOAUTH

**Comment by pergolafabio** [comment]
Post again your config how you changed

**Comment by pergolafabio** [comment]
Seems other people with that issue, could be dahua related...

https://community.freepbx.org/t/pjsip-phones-will-not-register/55213

**Comment by sohaibid** [comment]
yes I'm sure .
I'm using this password 
![image](https://github.com/TECH7Fox/asterisk-hass-addons/assets/39695223/8e99859b-dbef-4cdc-9c08-404d941c1bb9)

**Comment by pergolafabio** [comment]
You can they addind the identify section, not sure if it helps...

[8001]
type=identify
endpoint=8001
match="IP from your dahua here"

**Comment by pergolafabio** [comment]
But that screenshot is NOT the connection to asterisk, it's the private sip server on dahua itself!! You need to setup a trunk in astzriks to use that...

Search for the sip endpoint settings on your dahua

**Comment by sohaibid** [comment]
@pergolafabio gives '<sip:8001@192.168.1.102>' failed for '192.168.1.110:5060' (callid: 1888378726@192.168.1.110) - No matching endpoint found.

Have anyone tried with Hikvision?

**Comment by pergolafabio** [comment]
No mathing endpoint means that you probably don't have any diaplan for the extension you are calling...

Will be the same for hikvision

**Comment by pergolafabio** [comment]
I think it's best for you to join discord channel and ask for people that use same device as yours, so you can compare

**Comment by danielszilagyi** [comment]
I ran into issues like the ones posted here (couldn't register with the VTO) and the resolution was to set the SIP domain to 'asterisk' in the VTO SIP configuration. The Asterisk addon is using this as some default.

**Comment by Cr4z33** [comment]
> I ran into issues like the ones posted here (couldn't register with the VTO) and the resolution was to set the SIP domain to 'asterisk' in the VTO SIP configuration. The Asterisk addon is using this as some default.

Sorry for 'grave digging' this post, but I am in the same boat right now.

After attempting MANY times I would like to avoid having to factory reset everything  (VTO & VTH) as the VTO backup function is not working for some reason...

Are you 100% that entering SIP IP address `asterisk` only is enough to reach the addon? 🤔

**Comment by danielszilagyi** [comment]
I never stated to set the SIP IP address to asterisk. I commented about the SIP **domain**.

**Comment by Cr4z33** [comment]
> I never stated to set the SIP IP address to asterisk. I commented about the SIP **domain**.

Ooops my bad sorry!

May I ask you also how did you sort the issues with SSL certs (I keep getting `ERROR[667]: iostream.c:552 ast_iostream_close: SSL_shutdown() failed: error:00000001:lib(0)::reason(1), Internal SSL error`)?

I mean what solution did you use?
