### ISSUE TITLE
Mailbox server

### ISSUE THREAD

**Issue by TECH7Fox** [TECH7Fox/Asterisk-add-on#25]
Include a mailbox server which sends voicemails to later add to the integration.

**Comment by TECH7Fox** [comment]
https://www.home-assistant.io/docs/asterisk_mbox/

**Comment by freddeh** [comment]
For clarification, do I need to install anything beyond the asterisk add-on to use the mailbox functionality? Because if I enable it, the addon is in a boot loop and I am uncertain if I should open an issue or if I just missed something in the docs about installing another addon.
