### ISSUE TITLE
Add auto-discovery to quickly setup the integration

### ISSUE THREAD

**Issue by felipecrs** [TECH7Fox/Asterisk-add-on#30]
I found this reference here:

https://github.com/home-assistant/addons/blob/master/mosquitto/rootfs/etc/services.d/mosquitto/discovery

But I think we need to ensure the integration is installed, because differently from mosquitto (which is has official integration), it does not come installed by default in every HA installation.

This should help to solve https://github.com/TECH7Fox/Asterisk-add-on/pull/28 as well.

**Comment by TECH7Fox** [comment]
> But I think we need to ensure the integration is installed

After people install it from HACS, it should appear in some seconds right? That's good enough for now.

**Comment by felipecrs** [comment]
After installing from HACS, it also requires the restart of HA btw.

**Comment by TECH7Fox** [comment]
Add-on should now send the AMI config to HA.
