### ISSUE TITLE
Add more RTP ports as default

### ISSUE THREAD

**Issue by pergolafabio** [TECH7Fox/Asterisk-add-on#33]
started playing with video, but after second call, asterisk was already complaining about RDP
we need more as 8 as default for sure.... :-)

if you can make ranges now with the yaml method, maybe but it back on default setting?

**Comment by felipecrs** [comment]
Ref: https://community.home-assistant.io/t/add-support-for-port-ranges-in-add-on-config-yaml/375695/5

**Comment by felipecrs** [comment]
@TECH7Fox, @pergolafabio we can switch to `host_network` for now... but that's very sad.
