### ISSUE TITLE
Release strategy

### ISSUE THREAD

**Issue by felipecrs** [TECH7Fox/Asterisk-add-on#37]
Ok, so it turns out that the default CI is configured to build every merged PR on branch `main` and use the version set in config.yaml to tag it. This means that everytime we make a change even when not ready to release, the container gets built and the add-on gets updated in HA.

However, it won't notify users of an update, unless we actually change the version number.

This means that different people could potentially have the same version (v0.3.2) but they actually get different internal revisions of the add-on depending on when they installed.

In order to prevent this, we can work on a 2 branch model:

1. New features, fixes, or anything else goes as PRs to `develop` branch rather than `main` directly
2. Once we are done with the changes in `develop`, we create a commit in `develop` to ensure version is correct in `config.yaml` and also `CHANGELOG.md`.
3. We open a PR to merge `develop` in `main`.
4. After merging, we create a git tag matching the new version introduced by the above PR (i.e. `git tag v0.3.3-alpha origin/main && git push origin v0.3.3-alpha`) -> creating git tag is optional, but a good practice

PS: if we stick to versions with `-alpha` in name, we should write this in `config.yaml` as well:

```yaml
# config.yaml

version: 0.3.3-alpha
```

**Comment by TECH7Fox** [comment]
> PS: if we stick to versions with -alpha in name, we should write this in config.yaml as well

Lets not do that then. The 0 says that already anyways.

I set the branch rules, should be fine. I don't know if it is possible to always run the build tests only on `main`, to include in the protection rules.

**Comment by felipecrs** [comment]
> Lets not do that then. The 0 says that already anyways.

I agree!

**Comment by felipecrs** [comment]
> > PS: if we stick to versions with -alpha in name, we should write this in config.yaml as well
> 
> Lets not do that then. The 0 says that already anyways.
> 
> I set the branch rules, should be fine. I don't know if it is possible to always run the build tests only on `main`, to include in the protection rules.

I did already:

https://github.com/TECH7Fox/Asterisk-add-on/blob/main/.github/workflows/builder.yaml#L7-L14

The above means build will only run in main, but PRs against both develop and main will be tested.

**Comment by felipecrs** [comment]
@TECH7Fox, another thing:

I would suggest we don't use the GitHub Releases feature at all. The Home Assistant Supervisor panel only cares about the version in `config.yaml` and whatever is written in `CHANGELOG.md`.

Having to write GitHub Releases are doubled work IMO.

**Comment by TECH7Fox** [comment]
True, but it is easier to go back to previous versions. I don't mind making those releases, I just click on generate changelog. :)

**Comment by felipecrs** [comment]
> True, but it is easier to go back to previous versions.

You don't need the release for that, all you need is the tag only:

```console
$ git tag v0.3.3 origin/main

$ git push origin v0.3.3
```

Which can also be created through the UI.

**Comment by TECH7Fox** [comment]
When creating a release github makes a tag for you too. Takes like 5 seconds to make a release. And I like looking at those releases. You can easily see the progress and features added trough this project. 😄

**Comment by felipecrs** [comment]
Alright. Cool then. :-)
