### ISSUE TITLE
Add new UI/YAML config for enabling video support

### ISSUE THREAD

**Issue by felipecrs** [TECH7Fox/Asterisk-add-on#41]
It will then change the `videosupport=no` to `yes` on a per need basis.

Refs #39

**Comment by TECH7Fox** [comment]
The videosupport on the sipjs-card extensions right?

**Comment by felipecrs** [comment]
No, I mean this:

https://github.com/TECH7Fox/Asterisk-add-on/blob/develop/asterisk/rootfs/etc/asterisk/sip.conf#L7

**Comment by TECH7Fox** [comment]
Can't people set that in their custom extension? General also effects the sipjs-card extensions, and also possible breaks them when using the app.

**Comment by TECH7Fox** [comment]
Doesn't really make sense to add video support for custom extensions in [general] I think. The user should set that in their own extensions or marco's. 

I'm not sure if videosupport is needed to receive video, but if it is it would be useful if there was a option for that. At least until video doesn't crash the card sometimes.

**Comment by felipecrs** [comment]
It only crashes when using the companion app. So for those who does not use the companion app (like my tablet in kitchen with Fully Kiosk and `browser_mod`), it helpful to enable.

**Comment by TECH7Fox** [comment]
> it would be helpful to have the option to enable.

I agree. I will make a option to enable videosupport for [sipjs-card].
