### ISSUE TITLE
Request to have more logging

### ISSUE THREAD

**Issue by pergolafabio** [TECH7Fox/Asterisk-add-on#43]
As in topic, ssh addition on a specific custom port would be great to use asterisk cli commands

Thnx

**Comment by TECH7Fox** [comment]
I was thinking about the option to send commands via services from the integration or addon itself.

**Comment by pergolafabio** [comment]
If you set a command, for example debugging enabled, can you see the output then in the add-on log? Or whatever output is expected to see on a command?

**Comment by felipecrs** [comment]
This is not required guys. If you want to troubleshoot:

https://user-images.githubusercontent.com/29582865/148386885-6f165c34-5812-432b-8109-851510693fd3.mp4

**Comment by pergolafabio** [comment]
Yeah, I was indeed aware of that, but would have been a nice addition ;-)

**Comment by felipecrs** [comment]
What would be the use case? If it's just for debugging I don't see a need for more than that.

**Comment by pergolafabio** [comment]
Yes, like turning on sip debug for ex

But when can do it with workaround ;+)

**Comment by felipecrs** [comment]
We can add a new option like `log_debug` to increase the logs. When enabled, it configures logfiles.conf with more options, perhaps all the options.

**Comment by pergolafabio** [comment]
That's indeed interesting

**Comment by felipecrs** [comment]
Ref: https://github.com/TECH7Fox/Asterisk-add-on/commit/5b6c516879652aa92df6356c5e9df06f38c186c3

**Comment by pergolafabio** [comment]
> Ref: [5b6c516](https://github.com/TECH7Fox/Asterisk-add-on/commit/5b6c516879652aa92df6356c5e9df06f38c186c3)

Does it mean we now see less in addon log?

**Comment by felipecrs** [comment]
Yeah, I introduced that in a very old version, but then I reverted.

**Comment by pergolafabio** [comment]
is it possible to have  an option in the add-on config , that enables SIP debug logging?
checkbox for "SIP set debug on/off"

now, if we restart the add-on, we always need to enter the docker with a few commands and turn on debug
if we then do changes and need to restart, we again have todo the same :-)

**Comment by felipecrs** [comment]
I totally agree.

**Comment by felipecrs** [comment]
Ops :P

**Comment by TECH7Fox** [comment]
Btw, you can also change the `logger.conf` file in the Asterisk configs.

There are multiple logger options and I don't know how we could add those to the config. Checkbox for every type looks weird and string with the types isn't that user friendly.

**Comment by felipecrs** [comment]
We can have some presets. For example, we can start with "normal" (current) and "increased".

**Comment by TECH7Fox** [comment]
We could do that, but what if people want a specific combination? Then they can't change `logging.conf`.

**Comment by TECH7Fox** [comment]
Here are all the types:
```
;    debug
;    notice
;    warning
;    error
;    dtmf
;    fax
;    security
;    verbose(<level>)
```

The default conf is:
```
console => notice,warning,error
messages => notice,warning,error
```

**Comment by felipecrs** [comment]
I think 99% of the people will either want "normal" or "all"...

**Comment by felipecrs** [comment]
@pergolafabio WDYT?

**Comment by pergolafabio** [comment]
The most common command  I use is the debug one

**Comment by pergolafabio** [comment]
is the logger.conf now persistent after reboot?

**Comment by TECH7Fox** [comment]
Yes, you can change it however you want.

Maybe we will set it from presets, but then we can't modify the file ourself.

**Comment by pergolafabio** [comment]
ok, easier to change it ourselfs


is there a list of files now that we can change persistent?
so this can be closed, right?

**Comment by TECH7Fox** [comment]
> is there a list of files now that we can change persistent?

The only files you can't change are the auto generated ones. So every file in [this](https://github.com/TECH7Fox/Asterisk-add-on/tree/main/asterisk/rootfs/usr/share/tempio) folder.

> so this can be closed, right?

Yes, there is a permanent solution to customize your logs.

**Comment by TECH7Fox** [comment]
`log_level` option is added in the v1.3.1 update.
