### ISSUE TITLE
Cant add (Windows) SIP Softphone (Linphone)

### ISSUE THREAD

**Issue by dernassesmart** [TECH7Fox/Asterisk-add-on#53]
Wanted to add a softphone as testdevice. My target is to buy a "doorbird" doorbell device. It has sip functionality. Before buying the device, i wanted to test the sip functionality with a windows sip softphone (Linphone). But i get this error message in the logs:

[Jan  8 23:23:27]     -- Called SIP/100
[Jan  8 23:23:28]     -- SIP/100-00000028 is ringing
[Jan  8 23:23:31]   == Spawn extension (default, 100, 1) exited non-zero on 'SIP/101-00000027'
[Jan  8 23:23:35]   == WebSocket connection from '192.168.0.120:59669' for protocol 'sip' accepted using version '13'
[Jan  8 23:23:35]     -- Registered SIP '100' at 192.168.0.120:59669
[Jan  8 23:23:35]   == WebSocket connection from '192.168.0.120:59676' for protocol 'sip' accepted using version '13'
[Jan  8 23:23:35]     -- Registered SIP '100' at 192.168.0.120:59676
[Jan  8 23:23:39]   == WebSocket connection from '192.168.0.120:59684' for protocol 'sip' accepted using version '13'
[Jan  8 23:23:39]     -- Registered SIP '100' at 192.168.0.120:59684
[Jan  8 23:23:44]   == Using SIP RTP CoS mark 5
[Jan  8 23:23:44]     -- Executing [100@default:1] Dial("SIP/101-00000029", "SIP/100") in new stack
[Jan  8 23:23:44]   == Using SIP RTP CoS mark 5
[Jan  8 23:23:44] ERROR[1161][C-00000021]: netsock2.c:303 ast_sockaddr_resolve: getaddrinfo("vb6ed1uob25n.invalid", "(null)", ...): Name does not resolve
[Jan  8 23:23:44] WARNING[1161][C-00000021]: chan_sip.c:16938 __set_address_from_contact: Invalid host name in Contact: (can't resolve in DNS) : 'vb6ed1uob25n.invalid'
[Jan  8 23:23:44] ERROR[1161][C-00000021]: netsock2.c:96 ast_sockaddr_stringify_fmt: getnameinfo(): Unrecognized address family or invalid length
[Jan  8 23:23:44]     -- Called SIP/100
[Jan  8 23:23:44]     -- SIP/100-0000002a is ringing
[Jan  8 23:23:50]     -- SIP/100-0000002a answered SIP/101-00000029
[Jan  8 23:23:50]     -- Channel SIP/100-0000002a joined 'simple_bridge' basic-bridge <b66cbfa6-3271-4704-9e1f-fa7e7c5481aa>
[Jan  8 23:23:50]     -- Channel SIP/101-00000029 joined 'simple_bridge' basic-bridge <b66cbfa6-3271-4704-9e1f-fa7e7c5481aa>
[Jan  8 23:23:51] WARNING[1161][C-00000021]: res_rtp_asterisk.c:3179 __rtp_recvfrom: PJ ICE Rx error status code: 370400 'Bad Request'.
[Jan  8 23:23:51] WARNING[1161][C-00000021]: res_rtp_asterisk.c:7485 ast_rtp_read: RTP Read error: Invalid argument.  Hanging up.
[Jan  8 23:23:51]     -- Channel SIP/101-00000029 left 'simple_bridge' basic-bridge <b66cbfa6-3271-4704-9e1f-fa7e7c5481aa>
[Jan  8 23:23:51]   == Spawn extension (default, 100, 1) exited non-zero on 'SIP/101-00000029'
[Jan  8 23:23:51]     -- Channel SIP/100-0000002a left 'simple_bridge' basic-bridge <b66cbfa6-3271-4704-9e1f-fa7e7c5481aa>

ps: Homeassistant card to another homeassistant card (with two extension numbers) are working flawlessly!

**Comment by TECH7Fox** [comment]
How did you add the extension? could you share your `custom_sip.conf`?

**Comment by dernassesmart** [comment]
Hi TECH7Fox,

thanks for the reply. The extensions were added automatically from your asterisk addon. "Auto add extensions" is checked on. 
The sip_custom.conf is empty (except for the uncommented string):
> ; Place your own extensions here.

Everything is working with the Homeassistant Cards Only. But if i want to add a SIP Client (in this example, a sofphone named Linphone) it doesnt work.

**Comment by TECH7Fox** [comment]
Those extensions are only for the card. If you want to use a SIP device or application like Linphone you need to add a extension for that. 

Try this in `sip_custom.conf`:
```
[201]
type=friend
username=username
callerid= username <201> ; NO QUOTES!
context=internal
secret=1234abcd
qualify=no ; linphone will become unreachable if qualify=yes
host=dynamic
nat=no
canreinvite=yes
allow=!all,ulaw,alaw,gsm
```

You can set your own extension (replace 201), username and secret.

for more info: https://www.voip-info.org/asterisk-phone-linphone/

**Comment by dernassesmart** [comment]
Thank you very much!! It worked after i changed context=internal to 
> context=default

Perfect! I hope it will work with the doorbird device lawless too. I am very optimistic :).

**Comment by TECH7Fox** [comment]
Ah, my mistake. Good that you got it working!

Good luck with your doorbird device! Heard doorbird has great software.

**Comment by dernassesmart** [comment]
I hope so. I am very excited like a kid :D. I will tell you here, if it worked and how.

**Comment by mcarbonneaux** [comment]
i tryed the example, but get error :
```
[Jan 30 00:52:54] NOTICE[557]: res_pjsip/pjsip_distributor.c:676 log_failed_request: Request 'REGISTER' from '"username" <sip:username@192.168.50.2>' failed for '192.168.50.3:5060' (callid: iPDqei~QN3) - Failed to authenticate
```
192.168.50.3 = my ha with asterisk addon
192.168.50.3 = my linphone

![image](https://github.com/TECH7Fox/asterisk-hass-addons/assets/8479023/0cf834de-e22c-4bdf-a261-4114307a3481)

**Comment by TECH7Fox** [comment]
@mcarbonneaux did you create a endpoint for that in your pjsip_custom.conf?

**Comment by mcarbonneaux** [comment]
i found it !!! i tryed to create in sip_custom.conf in place of pjsip_custom.conf ! and now is working !

**Comment by pk802** [comment]
I have followed previous comments and put extensions in pjsip_custom.conf


```
; Place your custom extensions here
[201]
type=friend
username=user201
callerid= username <201> ; NO QUOTES!
context=default
secret=1234abcd
qualify=no ; linphone will become unreachable if qualify=yes
host=dynamic
nat=no
canreinvite=yes
allow=!all,ulaw,alaw,gsm


[202]
type=friend
username=user202
callerid= username <202> ; NO QUOTES!
context=default
secret=1234abcd
qualify=no ; linphone will become unreachable if qualify=yes
host=dynamic
nat=no
canreinvite=yes
allow=!all,ulaw,alaw,gsm
```


when I try to login using linphone I am getting 

[Feb 11 11:07:42] NOTICE[610]: res_pjsip/pjsip_distributor.c:673 log_failed_request: Request 'REGISTER' from '<sip:user201@192.168.29.30>' failed for '192.168.29.34:42752' (callid: qctyBv2~ZN) - No matching endpoint found
[Feb 11 11:07:42] NOTICE[610]: res_pjsip/pjsip_distributor.c:673 log_failed_request: Request 'REGISTER' from '<sip:user201@192.168.29.30>' failed for '192.168.29.34:42752' (callid: qctyBv2~ZN) - Failed to authenticate
