### ISSUE TITLE
config files for Asterisk wont update

### ISSUE THREAD

**Issue by Tekno-man** [TECH7Fox/Asterisk-add-on#61]
Installing the new version of the addon and running it with auto generate extensions doesn't verite old sip.conf file if previous version off extension used. To fix delete asterisk folder before installing new version

**Comment by felipecrs** [comment]
I still think we could always overwrite the files... or better yet only expose to /config/asterisk the ones we allow customization, like `sip_custom.conf`.

I have one idea:

sip.conf:
```
[general]
stuf = a
stuf = b

# include sip_custom.conf

# include sip_default.conf
``` 

sip_custom.conf:

```
; things in top goes to [general]

general-stuf = c

[1234]
custom-extension = 1
```

sip_default.conf (keep as today).
