### ISSUE TITLE
Move back translations to DOCS.md

### ISSUE THREAD

**Issue by felipecrs** [TECH7Fox/Asterisk-add-on#62]
Because the supervisor does not seem to support it right now.

**Comment by TECH7Fox** [comment]
I can safely remove `/translations/` right?

**Comment by felipecrs** [comment]
No, please keep the translations too. Only the `description` field of them are not taken into account by Supervisor (for now). But their `name`s are rendered in the UI.

So, I think the best is to keep both, at least until the Supervisor starts displaying the description of the attributes somewhere.

**Comment by TECH7Fox** [comment]
Alright, merged.
