### ISSUE TITLE
Fix video between card and add-on

### ISSUE THREAD

**Issue by TECH7Fox** [TECH7Fox/Asterisk-add-on#63]
Got this when trying to call with HA-SIP 0.2.6 with video enabled on both card and add-on.

```
[Jan 21 22:21:51]   == Using SIP VIDEO CoS mark 6
[Jan 21 22:21:51]   == Using SIP RTP CoS mark 5
[Jan 21 22:21:51] WARNING[515][C-00000002]: chan_sip.c:10921 process_sdp: Failed to receive SDP offer/answer with required SRTP crypto attributes for audio
```

Video enabled on add-on and disabled on card does work.

Got a `488 not acceptable here` from the card when video is enabled for card en disabled for add-on, as expected.

**Comment by thundergreen** [comment]
i confirm! video enabled in asterisk but disabled in card works

**Comment by TECH7Fox** [comment]
Fixed with HA-SIP 0.3.0.

**Comment by felipecrs** [comment]
Should we enable video support by default now?

**Comment by TECH7Fox** [comment]
> Should we enable video support by default now?

Yes, good idea.

**Comment by pergolafabio** [comment]
does it now also work on companion app?

**Comment by TECH7Fox** [comment]
Haven’t tried that, but don’t think it has access to the camera right? And it still needs to support the codecs.

https://github.com/onsip/SIP.js/issues/31
