### ISSUE TITLE
Allow for non-SSL installation for reverse proxy users

### ISSUE THREAD

**Issue by thewolfman56** [TECH7Fox/Asterisk-add-on#65]
This project looks to be a sorely needed integration for Home Assistant and I have been watching the vast amount of improvements that have been made in a short amount of time.

I can install this add-on without issue, but because I run Nginx outside of Home Assistant, no certificates are stored on my Home Assistant machine.  If I manually add the certificates to the /ssl directory, the add-on will start and I can add the integration, but any attempt at connection results in SSL errors.

If there is a way to get this add-on to work without local SSL certs, that would be greatly appreciated as I use reverse proxy for just a couple of machines.

**Comment by felipecrs** [comment]
Agreed. I suggest we add a new option like:

- [ ] SSL

Which can be deactivated in the configuration.

**Comment by felipecrs** [comment]
@thewolfman56 version 1.2.0 contains an option to disable any kind of TLS/HTTPS/SSL. Would you mind testing it in your reverse proxy setup? I would be extremely grateful.

Here is a guide on how to configure NGINX to proxy Asterisk's WebSockets interface:

https://warlord0blog.wordpress.com/2020/04/16/asterisk-webrtc/

**Comment by felipecrs** [comment]
Ok, I had to revert the feature added in 1.2.0, and now 1.3.0 contains an option called generate_ssl_cert, which comes disabled by default, but you probably want to enable it.

Then, you can configure your reverse proxy to proxy `https://<ha-ip>:8089`.
