### ISSUE TITLE
Not possible open configuration for Asterisk

### ISSUE THREAD

**Issue by TimpP-Spb** [TECH7Fox/Asterisk-add-on#67]
Hi!!
It can may be it is wrong, but when I try open configuration page by address localhost:5038 and i get error message:
Asterisk Call Manager/7.0.0
Response: Error
Message: Missing action in request

and in log file for Asterisk I see error:
[Jan 28 21:56:14]   == Client from 127.0.0.1, failed to authenticate in 30 seconds
[Jan 28 21:56:14]   == Connect attempt from '127.0.0.1' unable to authenticate
[Jan 28 21:56:16]   == Client from 127.0.0.1, failed to authenticate in 30 seconds
[Jan 28 21:56:16]   == Connect attempt from '127.0.0.1' unable to authenticate

**Comment by TECH7Fox** [comment]
Hi @TimpP-Spb,

Asterisk does not have a GUI. Only with FreePBX.

To configure the add-on, you can edit the files in `/config/asterisk` in HA and restart the add-on.

**Comment by TECH7Fox** [comment]
@TimpP-Spb are you still having problems?

**Comment by TECH7Fox** [comment]
No response. Reopen if you are still having problems.
